### ISSUE TITLE
你是要笑死我吗

### ISSUE THREAD

**Issue by cmd1152** [notewiki/notewiki.github.io#4]
> 欢迎来到 Note.ms Wiki！本站采用 [TiddlyWiki](https://tw-cn.netlify.app/) 。看起来本wiki好像可以编辑，但是只有Pull Request Marged并设置后才能保存。本wiki类似于[HC Wiki](https://hcwiki.github.io/)。但是权威性超过维基百科。
> 
> 本wiki包含Note.ms的方方面面，我们正在更新本wiki。如果你需要编辑，请参见[如何贡献](https://notewiki.github.io/#%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE)。
> 
> 注：404竟然冒充HC Wiki的创建者，HC Wiki明明是 4n0n4me 创建的。
> 
> 声明：最近有Hack.Chat成员[MelonCmd](https://notewiki.github.io/#MelonCmd)声称某个成员打广告提到“GitHub担保”，但纯属虚假！Googol没有声称“GitHub担保”，也没有证据。且GitHub Pages不对本wiki进行担保（补：SQL语句证据错误，无法证明MySQL中数据库内容不是伪造的）。Googol的HackChat被一些管理恶意封禁！

- 首先，你哪来的底气说权威性超过维基百科的？有证据吗（以其人之道还治其人之身），你不能证明权威性超过维基百科，**你主张**权威性超过维基百科，那么请举证！
- 其次，你做过的事情你自己清楚，还《没有声称》，需要我把4n0n4me和0x24a喊过来证明吗？
- 然后，你知道为什么你被封禁吗？你自己刷屏被ban！

###### 最后看这个

> 404虽然可以指HTTP错误码，但是在Note.ms的404也是一个用户。其态度过激，喜欢随意辱骂Googol。甚至尝试冒充[4n0n4me](https://notewiki.github.io/#4n0n4me)，可[MelonCmd](https://notewiki.github.io/#MelonCmd)却支持他们的观点。其是一位[Note.msBBS](https://notewiki.github.io/#Note.msBBS)站长，支持[Anonymous_user](https://notewiki.github.io/#Anonymous_user)的观点。是[HcBBs](https://notewiki.github.io/#HcBBs)的全板块版主。
> 
> 在原[公平论坛](https://notewiki.github.io/#%E5%85%AC%E5%B9%B3%E8%AE%BA%E5%9D%9B)中发布过关于“鸭子测试”（如果一个东西像鸭子，闻起来像鸭子，走起来像鸭子，听起来像鸭子，那么他就是一只鸭子）的言论。

我笑了，需要我把**4n0n4me**给at过来吗，哦不对，我at了你肯定会说这个4n0n4me**也**是404冒充的hhh

> 22c是[22c组](https://notewiki.github.io/#22c%E7%BB%84)成员，其极力反对Googol，甚至搞轰炸机、进行DDoS攻击。恶意攻击网站[NeBBs](https://notewiki.github.io/#NeBBs)导致被InfinityFree封禁（原话如此：suspended）。

你这个语句也不清楚啊，22c没被ban，被ban的是你的fake website（模仿某个人用fake）

> Q：Gongxiang01是Googol吗？
> A：绝对不是！但是还是有很多人不知道，说也不承认。

呀，是谁忘记删除了Gongxiang01的github个人简介说自己是Googol的那段~

>[ProtectNote](https://notewiki.github.io/#ProtectNote) - 保护组织，旨在对被CleanNote毁灭的页面进行保护。

那么请问这个组织保护了哪些页面捏~
为什么我现在打开你保护的页面，却是被破坏的
保护了个寂寞啊

**Comment by Googologyer** [comment]
第一，权威性超过维基百科，经过检查发现*Jimmy Wales*冒充，已经删除

**Comment by Googologyer** [comment]
第二第三，你没有证据。另外404不是4n0n4me。另外，确实是我的网站被封。“是谁忘记删除了Gongxiang01的github个人简介说自己是Googol的那段~”？？？

**Comment by Googologyer** [comment]
ProtectNote保护了/1-/500等页面。如果需要保护请在我论坛提出

**Comment by Googologyer** [comment]
锁

**Comment by 0x24a** [comment]
nerd
